export const sectors = {
    1: "Commercial Banks",
    2: "Corporate Debenture",
    3: "Development Banks",
    4: "Finance",
    6: "Hotels and Tourism",
    7: "Hydro Power",
    8: "Investment",
    9: "Life Insurance",
    10: "Manufacturing and Processing",
    11: "Microfinance",
    12: "Mutual Fund",
    13: "Non Life Insurance",
    14: "Others",
    16: "Tradings",
};
export const companies = [
    {
        "i": 588,
        "name": "Aarambha Chautari Laghubitta Bittiya Sanstha Limited",
        "symbol": "ACLBSL",
        "sid": 11,
    },
    {
        "i": 908,
        "name": "Aarambha Chautari Laghubitta Bittiya Sanstha Limited Promoter Share",
        "symbol": "ACLBSLP",
        "sid": 11,
    },
    {
        "i": 1,
        "name": "Agricultural Development Bank Limited",
        "symbol": "ADBL",
        "sid": 1,
    },
    {
        "i": 930,
        "name": "Agricultural Development Bank Limited Promoter Share",
        "symbol": "ADBLP",
        "sid": 1,
    },
    {
        "i": 766,
        "name": "Adarsha Laghubitta Bittiya Sanstha Limited",
        "symbol": "ADLB",
        "sid": 11,
    },
    {
        "i": 783,
        "name": "Adarsha Laghubitta Bittiya Sanstha Limited Promoter Share",
        "symbol": "ADLBP",
        "sid": 11,
    },
    {
        "i": 804,
        "name": "Asian Hydropower Limited",
        "symbol": "AHL",
        "sid": 7,
    },
    {
        "i": 152,
        "name": "Arun Valley Hydropower Development Co. Ltd.",
        "symbol": "AHPC",
        "sid": 7,
    },
    {
        "i": 581,
        "name": "Ajod Insurance Limited",
        "symbol": "AIL",
        "sid": 13,
    },
    {
        "i": 257,
        "name": "Adhikhola Laghubitta Bittiya Sanstha Limited",
        "symbol": "AKBSL",
        "sid": 11,
    },
    {
        "i": 149,
        "name": "Ankhu Khola Jalvidhyut Company Ltd",
        "symbol": "AKJCL",
        "sid": 7,
    },
    {
        "i": 151,
        "name": "Arun Kabeli Power Ltd.",
        "symbol": "AKPL",
        "sid": 7,
    },
    {
        "i": 259,
        "name": "Asha Laghubitta Bittiya Sanstha Ltd",
        "symbol": "ALBSL",
        "sid": 11,
    },
    {
        "i": 260,
        "name": "Asha Laghubitta Bittiya Sanstha Limited Promoter Share",
        "symbol": "ALBSLP",
        "sid": 11,
    },
    {
        "i": 241,
        "name": "Asian Life Insurance Co. Limited",
        "symbol": "ALICL",
        "sid": 9,
    },
    {
        "i": 242,
        "name": "Asian Life Insurance Company Limited Promoter Share",
        "symbol": "ALICLP",
        "sid": 9,
    },
    {
        "i": 818,
        "name": "Aatmanirbhar Laghubitta Bittiya Sanstha",
        "symbol": "ANLB",
        "sid": 11,
    },
    {
        "i": 865,
        "name": "Aatmanirbhar Laghubitta Bittiya Sanstha Promoter",
        "symbol": "ANLBP",
        "sid": 11,
    },
    {
        "i": 150,
        "name": "Api Power Company Ltd.",
        "symbol": "API",
        "sid": 7,
    },
    {
        "i": 780,
        "name": "Aviyan Lagubitta Bittiya Sanstha Limited",
        "symbol": "AVYAN",
        "sid": 11,
    },
    {
        "i": 153,
        "name": "Barun Hydropower Co. Ltd.",
        "symbol": "BARUN",
        "sid": 7,
    },
    {
        "i": 232,
        "name": "Bishal Bazar Company Limited",
        "symbol": "BBC",
        "sid": 16,
    },
    {
        "i": 821,
        "name": "Bhugol Energy Development Company Limited",
        "symbol": "BEDC",
        "sid": 7,
    },
    {
        "i": 106,
        "name": "Best Finance Company Ltd.",
        "symbol": "BFC",
        "sid": 4,
    },
    {
        "i": 107,
        "name": "Best Finance Company Limited Promoter Share",
        "symbol": "BFCPO",
        "sid": 4,
    },
    {
        "i": 859,
        "name": "Bhagwati Hydropower Development Company Limited",
        "symbol": "BGWT",
        "sid": 7,
    },
    {
        "i": 751,
        "name": "Bindhyabasini Hydropower Development Company Limited",
        "symbol": "BHDC",
        "sid": 7,
    },
    {
        "i": 688,
        "name": "Balephi Hydropower Limited",
        "symbol": "BHL",
        "sid": 7,
    },
    {
        "i": 796,
        "name": "Barahi Hydropower Public Limited",
        "symbol": "BHPL",
        "sid": 7,
    },
    {
        "i": 669,
        "name": "Buddha Bhumi Nepal Hydropower Company Limited",
        "symbol": "BNHC",
        "sid": 7,
    },
    {
        "i": 235,
        "name": "Bottlers Nepal (Balaju) Limited",
        "symbol": "BNL",
        "sid": 10,
    },
    {
        "i": 234,
        "name": "Bottlers Nepal (Terai) Limited",
        "symbol": "BNT",
        "sid": 10,
    },
    {
        "i": 2,
        "name": "Bank of Kathmandu Ltd.",
        "symbol": "BOKL",
        "sid": 1,
    },
    {
        "i": 154,
        "name": "Butwal Power Company Limited",
        "symbol": "BPCL",
        "sid": 7,
    },
    {
        "i": 707,
        "name": "BPW Laghubitta Bittiya Sanstha Limited",
        "symbol": "BPW",
        "sid": 11,
    },
    {
        "i": 871,
        "name": "BPW Laghubitta Bittiya Sanstha Limited Promoter Share",
        "symbol": "BPWP",
        "sid": 11,
    },
    {
        "i": 263,
        "name": "Chhimek Laghubitta Bittiya Sanstha Limited",
        "symbol": "CBBL",
        "sid": 11,
    },
    {
        "i": 264,
        "name": "Chhimek Laghubitta Bittiya Sanstha Limited Promoter Share",
        "symbol": "CBBLPO",
        "sid": 11,
    },
    {
        "i": 8,
        "name": "Civil Bank Ltd",
        "symbol": "CBL",
        "sid": 1,
    },
    {
        "i": 9,
        "name": "Civil Bank Limited Promoter Share",
        "symbol": "CBLPO",
        "sid": 1,
    },
    {
        "i": 4,
        "name": "Century Commercial Bank Ltd.",
        "symbol": "CCBL",
        "sid": 1,
    },
    {
        "i": 5,
        "name": "Century Commercial Bank Limited Promoter Share",
        "symbol": "CCBLPO",
        "sid": 1,
    },
    {
        "i": 110,
        "name": "Central Finance Limited",
        "symbol": "CFCL",
        "sid": 4,
    },
    {
        "i": 111,
        "name": "Central Finance Limited Promoter Share",
        "symbol": "CFCLPO",
        "sid": 4,
    },
    {
        "i": 607,
        "name": "Chandragiri Hills Limited",
        "symbol": "CGH",
        "sid": 6,
    },
    {
        "i": 156,
        "name": "Chilime Hydropower Company Limited",
        "symbol": "CHCL",
        "sid": 7,
    },
    {
        "i": 692,
        "name": "CEDB Hydropower Development Co. Ltd.",
        "symbol": "CHDC",
        "sid": 8,
    },
    {
        "i": 155,
        "name": "Chhyangdi Hydropower Ltd.",
        "symbol": "CHL",
        "sid": 7,
    },
    {
        "i": 229,
        "name": "Citizen Investment Trust",
        "symbol": "CIT",
        "sid": 8,
    },
    {
        "i": 927,
        "name": "Citizen Investment Trust Promoter Share",
        "symbol": "CITPO",
        "sid": 8,
    },
    {
        "i": 838,
        "name": "City Hotel Limited",
        "symbol": "CITY",
        "sid": 6,
    },
    {
        "i": 863,
        "name": "Chirkhwa Hydro Power Ltd",
        "symbol": "CKHL",
        "sid": 7,
    },
    {
        "i": 265,
        "name": "Civil Laghubitta Bittiya Sanstha Limited Promoter Share",
        "symbol": "CLBSLP",
        "sid": 11,
    },
    {
        "i": 671,
        "name": "Citizen Life Insurance Company Limited",
        "symbol": "CLI",
        "sid": 9,
    },
    {
        "i": 903,
        "name": "Citizen Life Insurance Company Limited Promoter Share",
        "symbol": "CLIP",
        "sid": 9,
    },
    {
        "i": 53,
        "name": "Corporate Development Bank Limited",
        "symbol": "CORBL",
        "sid": 3,
    },
    {
        "i": 54,
        "name": "Corporate Development Bank Limited Promoter Share",
        "symbol": "CORBLP",
        "sid": 3,
    },
    {
        "i": 716,
        "name": "CYC Nepal Laghubitta Bittiya Sanstha Limited",
        "symbol": "CYCL",
        "sid": 11,
    },
    {
        "i": 772,
        "name": "CYC Nepal Laghubitta Bittiya Sanstha Ltd- Promotor Share",
        "symbol": "CYCLP",
        "sid": 11,
    },
    {
        "i": 6,
        "name": "Citizen Bank International Limited",
        "symbol": "CZBIL",
        "sid": 1,
    },
    {
        "i": 7,
        "name": "Citizens Bank International Limited Promoter Share",
        "symbol": "CZBILP",
        "sid": 1,
    },
    {
        "i": 267,
        "name": "Deprosc Laghubitta Bittiya Sanstha Limited",
        "symbol": "DDBL",
        "sid": 11,
    },
    {
        "i": 268,
        "name": "Deprosc Laghubitta Bittiya Sanstha Limited Promoter Share",
        "symbol": "DDBLPO",
        "sid": 11,
    },
    {
        "i": 157,
        "name": "Dibyashwori Hydropower Ltd.",
        "symbol": "DHPL",
        "sid": 7,
    },
    {
        "i": 779,
        "name": "Dhaulagiri Lagubitta Bittiya Sanstha Limited",
        "symbol": "DLBS",
        "sid": 11,
    },
    {
        "i": 799,
        "name": "Dhaulagiri Lagubitta Bittiya Sanstha Limited Promoter Share",
        "symbol": "DLBSP",
        "sid": 11,
    },
    {
        "i": 825,
        "name": "Dolti Power Company Limited",
        "symbol": "DOLTI",
        "sid": 7,
    },
    {
        "i": 752,
        "name": "Dordi Khola Jal Bidyut Company Limited",
        "symbol": "DORDI",
        "sid": 7,
    },
    {
        "i": 10,
        "name": "Everest Bank Limited",
        "symbol": "EBL",
        "sid": 1,
    },
    {
        "i": 11,
        "name": "Everest Bank Limited Promoter Share",
        "symbol": "EBLPO",
        "sid": 1,
    },
    {
        "i": 57,
        "name": "Excel Development Bank Ltd.",
        "symbol": "EDBL",
        "sid": 3,
    },
    {
        "i": 58,
        "name": "Excel Development Bank Limited Promoter Share",
        "symbol": "EDBLPO",
        "sid": 3,
    },
    {
        "i": 786,
        "name": "Eastern Hydropower Company Limited",
        "symbol": "EHPL",
        "sid": 7,
    },
    {
        "i": 199,
        "name": "Everest Insurance Co. Ltd.",
        "symbol": "EIC",
        "sid": 13,
    },
    {
        "i": 200,
        "name": "Everest Insurance Company Limited Promoter Share",
        "symbol": "EICPO",
        "sid": 13,
    },
    {
        "i": 742,
        "name": "Emerging Nepal Limited",
        "symbol": "ENL",
        "sid": 8,
    },
    {
        "i": 745,
        "name": "Emerging Nepal Limited Promoter Share",
        "symbol": "ENLP",
        "sid": 8,
    },
    {
        "i": 269,
        "name": "First Micro Finance Development Bank Ltd.",
        "symbol": "FMDBL",
        "sid": 11,
    },
    {
        "i": 270,
        "name": "First Microfinance Laghubitta Bittiya Sanstha Limited Promoter Share",
        "symbol": "FMDBLP",
        "sid": 11,
    },
    {
        "i": 271,
        "name": "Forward Microfinance Laghubitta Bittiya Sanstha Limited",
        "symbol": "FOWAD",
        "sid": 11,
    },
    {
        "i": 272,
        "name": "Forward Community Microfinance Bittiya Sanstha Limited Promoter Share",
        "symbol": "FOWADP",
        "sid": 11,
    },
    {
        "i": 61,
        "name": "Garima Bikas Bank Limited",
        "symbol": "GBBL",
        "sid": 3,
    },
    {
        "i": 62,
        "name": "Garima Bikas Bank Limited Promoter Share",
        "symbol": "GBBLPO",
        "sid": 3,
    },
    {
        "i": 12,
        "name": "Global IME Bank Limited",
        "symbol": "GBIME",
        "sid": 1,
    },
    {
        "i": 13,
        "name": "Global IME Bank Limited Promoter Share",
        "symbol": "GBIMEP",
        "sid": 1,
    },
    {
        "i": 279,
        "name": "Grameen Bikas Laghubitta Bittiya Sanstha Ltd.",
        "symbol": "GBLBS",
        "sid": 11,
    },
    {
        "i": 280,
        "name": "Grameen Bikas Laghubitta Bittiya Sanstha Limited Promoter Share",
        "symbol": "GBLBSP",
        "sid": 11,
    },
    {
        "i": 847,
        "name": "Ghorahi Cement Industry Ltd.",
        "symbol": "GCIL",
        "sid": 10,
    },
    {
        "i": 114,
        "name": "Goodwill Finance Co. Ltd.",
        "symbol": "GFCL",
        "sid": 4,
    },
    {
        "i": 115,
        "name": "Goodwill Finance Company Limited Promoter Share",
        "symbol": "GFCLPO",
        "sid": 4,
    },
    {
        "i": 276,
        "name": "Ghodighoda Laghubitta Bittiya Sanstha Limited Promoter Share",
        "symbol": "GGBSLPO",
        "sid": 11,
    },
    {
        "i": 158,
        "name": "Ghalemdi Hydro Limited",
        "symbol": "GHL",
        "sid": 7,
    },
    {
        "i": 601,
        "name": "General Insurance Company Nepal Ltd",
        "symbol": "GIC",
        "sid": 13,
    },
    {
        "i": 278,
        "name": "Global IME Laghubitta Bittiya Sanstha Ltd.",
        "symbol": "GILB",
        "sid": 11,
    },
    {
        "i": 277,
        "name": "Global IME Laghubitta Bittiya Sanstha Limited Promoter Share",
        "symbol": "GILBPO",
        "sid": 11,
    },
    {
        "i": 282,
        "name": "Gurans Laghubitta Bittiya Sanstha Limited",
        "symbol": "GLBSL",
        "sid": 11,
    },
    {
        "i": 281,
        "name": "Gurans Laghubitta Bittiya Sanstha Limited Promoter Share",
        "symbol": "GLBSLP",
        "sid": 11,
    },
    {
        "i": 577,
        "name": "Greenlife Hydropower Limited",
        "symbol": "GLH",
        "sid": 7,
    },
    {
        "i": 243,
        "name": "Gurans Life Insurance Company Ltd.",
        "symbol": "GLICL",
        "sid": 9,
    },
    {
        "i": 244,
        "name": "Gurans Life Insurance Company Limited Promoter Share",
        "symbol": "GLICLP",
        "sid": 9,
    },
    {
        "i": 273,
        "name": "Ganapati Laghubitta Bittiya Sanstha Limited",
        "symbol": "GMFBS",
        "sid": 11,
    },
    {
        "i": 274,
        "name": "Ganapati Laghubitta Bittiya Sanstha Limited Promoter Share",
        "symbol": "GMFBSP",
        "sid": 11,
    },
    {
        "i": 116,
        "name": "Guheshowori Merchant Bank & Finance Co. Ltd.",
        "symbol": "GMFIL",
        "sid": 4,
    },
    {
        "i": 117,
        "name": "Guheswori Merchant Banking and Finance Limited Promoter Share",
        "symbol": "GMFILP",
        "sid": 4,
    },
    {
        "i": 63,
        "name": "Green Development Bank Ltd.",
        "symbol": "GRDBL",
        "sid": 3,
    },
    {
        "i": 64,
        "name": "Green Development Bank Limited Promoter Share",
        "symbol": "GRDBLP",
        "sid": 3,
    },
    {
        "i": 118,
        "name": "Gurkhas Finance Ltd.",
        "symbol": "GUFL",
        "sid": 4,
    },
    {
        "i": 119,
        "name": "Gurkhas Finance Limited Promoter Share",
        "symbol": "GUFLPO",
        "sid": 4,
    },
    {
        "i": 687,
        "name": "Green Venture Limited",
        "symbol": "GVL",
        "sid": 7,
    },
    {
        "i": 885,
        "name": "Hathway Investment Nepal Limited",
        "symbol": "HATHY",
        "sid": 8,
    },
    {
        "i": 14,
        "name": "Himalayan Bank Limited",
        "symbol": "HBL",
        "sid": 1,
    },
    {
        "i": 15,
        "name": "Himalayan Bank Limited Promoter Share",
        "symbol": "HBLPO",
        "sid": 1,
    },
    {
        "i": 355,
        "name": "Himal Dolakha Hydropower Company Limited",
        "symbol": "HDHPC",
        "sid": 7,
    },
    {
        "i": 236,
        "name": "Himalayan Distillery Limited",
        "symbol": "HDL",
        "sid": 10,
    },
    {
        "i": 787,
        "name": "Himalayan Everest Insurance Limited",
        "symbol": "HEI",
        "sid": 13,
    },
    {
        "i": 788,
        "name": "Himalayan Everest Insurance Company Limited-Promoter Share.",
        "symbol": "HEIP",
        "sid": 13,
    },
    {
        "i": 201,
        "name": "Himalayan General Insurance Co. Ltd",
        "symbol": "HGI",
        "sid": 13,
    },
    {
        "i": 202,
        "name": "Himalayan General Insurance Company Limited Promoter Share",
        "symbol": "HGIPO",
        "sid": 13,
    },
    {
        "i": 756,
        "name": "Himalayan Hydropower Limited",
        "symbol": "HHL",
        "sid": 7,
    },
    {
        "i": 230,
        "name": "Hydorelectricity Investment and Development Company Ltd",
        "symbol": "HIDCL",
        "sid": 8,
    },
    {
        "i": 795,
        "name": "Hydorelectricity Investment and Development Company Ltd Promoter Share",
        "symbol": "HIDCLP",
        "sid": 8,
    },
    {
        "i": 266,
        "name": "Himalayan Laghubitta Bittiya Sanstha Limited",
        "symbol": "HLBSL",
        "sid": 11,
    },
    {
        "i": 869,
        "name": "Himalayan Life Insurance Limited",
        "symbol": "HLI",
        "sid": 9,
    },
    {
        "i": 881,
        "name": "Himalayan Life Insurance Limited- Promoter Shares",
        "symbol": "HLIPO",
        "sid": 9,
    },
    {
        "i": 160,
        "name": "Himalayan Power Partner Ltd.",
        "symbol": "HPPL",
        "sid": 7,
    },
    {
        "i": 906,
        "name": "Himalayan Re-Insurance Limited",
        "symbol": "HRL",
        "sid": 14,
    },
    {
        "i": 916,
        "name": "Himalayan Re-Insurance Limited Promoter Share",
        "symbol": "HRLP",
        "sid": 14,
    },
    {
        "i": 159,
        "name": "Himalaya Urja Bikas Company Limited",
        "symbol": "HURJA",
        "sid": 7,
    },
    {
        "i": 120,
        "name": "ICFC Finance Limited",
        "symbol": "ICFC",
        "sid": 4,
    },
    {
        "i": 121,
        "name": "ICFC Finance Limited Promoter Share",
        "symbol": "ICFCPO",
        "sid": 4,
    },
    {
        "i": 868,
        "name": "IGI Prudential Insurance Limited",
        "symbol": "IGI",
        "sid": 13,
    },
    {
        "i": 204,
        "name": "IME General Insurance Limited Promoter Share",
        "symbol": "IGIPO",
        "sid": 13,
    },
    {
        "i": 830,
        "name": "Ingwa Hydropower Limited",
        "symbol": "IHL",
        "sid": 7,
    },
    {
        "i": 283,
        "name": "Infinity Laghubitta Bittiya Sanstha Limited",
        "symbol": "ILBS",
        "sid": 11,
    },
    {
        "i": 284,
        "name": "Infinity Laghubitta Bittiya Sanstha Limited Promoter Share",
        "symbol": "ILBSP",
        "sid": 11,
    },
    {
        "i": 866,
        "name": "IME Life Insurance Company Limited",
        "symbol": "ILI",
        "sid": 9,
    },
    {
        "i": 897,
        "name": "IME Life Insurance Company Limited Promoter Share",
        "symbol": "ILIP",
        "sid": 9,
    },
    {
        "i": 741,
        "name": "Jalpa Samudayik Laghubitta Bittiya Sanstha Limited",
        "symbol": "JALPA",
        "sid": 11,
    },
    {
        "i": 747,
        "name": "Jalpa Samudayik Laghubitta Bittiya Sanstha Limited Promoter Share",
        "symbol": "JALPAP",
        "sid": 11,
    },
    {
        "i": 65,
        "name": "Jyoti Bikas Bank Limited",
        "symbol": "JBBL",
        "sid": 3,
    },
    {
        "i": 66,
        "name": "Jyoti Bikas Bank Limited Promoter Share",
        "symbol": "JBBLPO",
        "sid": 3,
    },
    {
        "i": 680,
        "name": "Jeevan Bikas Laghubitta Bittiya Sanstha Limited",
        "symbol": "JBLB",
        "sid": 11,
    },
    {
        "i": 721,
        "name": "Jeevan Bikas Laghubitta Bittiya Sanstha Limited -Promoter Share",
        "symbol": "JBLBP",
        "sid": 11,
    },
    {
        "i": 122,
        "name": "Janaki Finance Company Ltd.",
        "symbol": "JFL",
        "sid": 4,
    },
    {
        "i": 123,
        "name": "Janaki Finance company Limited Promoter Share",
        "symbol": "JFLPO",
        "sid": 4,
    },
    {
        "i": 677,
        "name": "Jyoti Life Insurance Company Ltd",
        "symbol": "JLI",
        "sid": 9,
    },
    {
        "i": 691,
        "name": "Jyoti Life Insurance Company Ltd.- Promoter Share",
        "symbol": "JLIP",
        "sid": 9,
    },
    {
        "i": 161,
        "name": "Joshi Hydropower Development Company Ltd",
        "symbol": "JOSHI",
        "sid": 7,
    },
    {
        "i": 286,
        "name": "Janautthan Samudayik Laghubitta Bittiya Sanstha Limited",
        "symbol": "JSLBB",
        "sid": 11,
    },
    {
        "i": 285,
        "name": "Janautthan Samudayic Laghubitta Bikas Bank Limited Promoter Share",
        "symbol": "JSLBBP",
        "sid": 11,
    },
    {
        "i": 18,
        "name": "Kumari Bank Limited",
        "symbol": "KBL",
        "sid": 1,
    },
    {
        "i": 19,
        "name": "Kumari Bank Limited Promoter Share",
        "symbol": "KBLPO",
        "sid": 1,
    },
    {
        "i": 855,
        "name": "Kutheli Bukhari Small Hydropower Ltd",
        "symbol": "KBSH",
        "sid": 7,
    },
    {
        "i": 801,
        "name": "Kalinchwok Darshan Limited",
        "symbol": "KDL",
        "sid": 6,
    },
    {
        "i": 163,
        "name": "Khanikhola Hydropower Co. Ltd.",
        "symbol": "KKHC",
        "sid": 7,
    },
    {
        "i": 734,
        "name": "Khaptad Laghubitta Bittiya Sanstha Limited",
        "symbol": "KLBS",
        "sid": 11,
    },
    {
        "i": 591,
        "name": "Kisan Lagubitta Bittiya Sanstha Limited",
        "symbol": "KLBSL",
        "sid": 11,
    },
    {
        "i": 610,
        "name": "Kisan Lagubitta Bittiya Sanstha Limited Promotor Share",
        "symbol": "KLBSLP",
        "sid": 11,
    },
    {
        "i": 798,
        "name": "Khaptad Laghubitta Bittiya Sanstha Limited Promoter Share",
        "symbol": "KLBSP",
        "sid": 11,
    },
    {
        "i": 287,
        "name": "Kalika Laghubitta Bittiya Sanstha Limited",
        "symbol": "KMCDB",
        "sid": 11,
    },
    {
        "i": 288,
        "name": "Kalika Laghubitta Bittiya Sanstha Limited Promoter Share",
        "symbol": "KMCDBP",
        "sid": 11,
    },
    {
        "i": 162,
        "name": "Kalika Power Company Ltd",
        "symbol": "KPCL",
        "sid": 7,
    },
    {
        "i": 75,
        "name": "Karnali Development Bank Limited",
        "symbol": "KRBL",
        "sid": 3,
    },
    {
        "i": 76,
        "name": "Karnali Development Bank Limited Promoter Share",
        "symbol": "KRBLPO",
        "sid": 3,
    },
    {
        "i": 69,
        "name": "Kamana Sewa Bikas Bank Limited",
        "symbol": "KSBBL",
        "sid": 3,
    },
    {
        "i": 70,
        "name": "Kamana Sewa Bikas Bank Limited Promoter Share",
        "symbol": "KSBBLP",
        "sid": 3,
    },
    {
        "i": 77,
        "name": "Lumbini Bikas Bank Ltd.",
        "symbol": "LBBL",
        "sid": 3,
    },
    {
        "i": 78,
        "name": "Lumbini Bikas Bank Limited Promoter Share",
        "symbol": "LBBLPO",
        "sid": 3,
    },
    {
        "i": 20,
        "name": "Laxmi Bank Limited",
        "symbol": "LBL",
        "sid": 1,
    },
    {
        "i": 21,
        "name": "Laxmi Bank Limited Promoter Share",
        "symbol": "LBLPO",
        "sid": 1,
    },
    {
        "i": 573,
        "name": "Liberty Energy Company Limited",
        "symbol": "LEC",
        "sid": 7,
    },
    {
        "i": 205,
        "name": "Lumbini General Insurance Co. Ltd.",
        "symbol": "LGIL",
        "sid": 13,
    },
    {
        "i": 206,
        "name": "Lumbini General Insurance Company Limited Promoter Share",
        "symbol": "LGILPO",
        "sid": 13,
    },
    {
        "i": 245,
        "name": "Life Insurance Corporation (Nepal) Limited",
        "symbol": "LICN",
        "sid": 9,
    },
    {
        "i": 246,
        "name": "Life Insurance Corporation (Nepal) Limited Promoter Share",
        "symbol": "LICNPO",
        "sid": 9,
    },
    {
        "i": 291,
        "name": "Laxmi Laghubitta Bittiya Sanstha Ltd.",
        "symbol": "LLBS",
        "sid": 11,
    },
    {
        "i": 292,
        "name": "Laxmi Laghubitta Bittiya Sanstha Limited Promoter Share",
        "symbol": "LLBSPO",
        "sid": 11,
    },
    {
        "i": 883,
        "name": "Laxmi Sunrise Bank Limited",
        "symbol": "LSL",
        "sid": 1,
    },
    {
        "i": 817,
        "name": "Makar Jitumaya Suri Hydropower Limited",
        "symbol": "MAKAR",
        "sid": 7,
    },
    {
        "i": 858,
        "name": "Mandu Hydropower Limited",
        "symbol": "MANDU",
        "sid": 7,
    },
    {
        "i": 939,
        "name": "Matribhumi Laghubitta Bittiya Sanstha Limited",
        "symbol": "MATRI",
        "sid": 11,
    },
    {
        "i": 940,
        "name": "Matribhumi Laghubitta Bittiya Sanstha Promoter Share",
        "symbol": "MATRIP",
        "sid": 11,
    },
    {
        "i": 696,
        "name": "Madhya Bhotekoshi Jalavidyut Company Limited",
        "symbol": "MBJC",
        "sid": 7,
    },
    {
        "i": 22,
        "name": "Machhapuchhre Bank Limited",
        "symbol": "MBL",
        "sid": 1,
    },
    {
        "i": 23,
        "name": "Machhapuchchhre Bank Limited Promoter Share",
        "symbol": "MBLPO",
        "sid": 1,
    },
    {
        "i": 822,
        "name": "Menchhiyam Hydropower Limited",
        "symbol": "MCHL",
        "sid": 7,
    },
    {
        "i": 81,
        "name": "Miteri Development Bank Limited",
        "symbol": "MDB",
        "sid": 3,
    },
    {
        "i": 82,
        "name": "Miteri Development Bank Limited Promoter Share",
        "symbol": "MDBPO",
        "sid": 3,
    },
    {
        "i": 24,
        "name": "Mega Bank Nepal Ltd.",
        "symbol": "MEGA",
        "sid": 1,
    },
    {
        "i": 25,
        "name": "Mega Bank Nepal Limited Promoter Share",
        "symbol": "MEGAPO",
        "sid": 1,
    },
    {
        "i": 861,
        "name": "Manakamana Engineering Hydropower Limited",
        "symbol": "MEHL",
        "sid": 7,
    },
    {
        "i": 832,
        "name": "Modi Energy Limited",
        "symbol": "MEL",
        "sid": 7,
    },
    {
        "i": 603,
        "name": "Mountain Energy Nepal Limited",
        "symbol": "MEN",
        "sid": 7,
    },
    {
        "i": 297,
        "name": "Mero Microfinance Laghubitta Bittiya Sanstha Limited",
        "symbol": "MERO",
        "sid": 11,
    },
    {
        "i": 298,
        "name": "Mero Microfinance Laghubitta Bittiya Sanstha Limited Promoter Share",
        "symbol": "MEROPO",
        "sid": 11,
    },
    {
        "i": 126,
        "name": "Manjushree Finance Ltd.",
        "symbol": "MFIL",
        "sid": 4,
    },
    {
        "i": 127,
        "name": "Manjushree Finance Limited Promoter Share",
        "symbol": "MFILPO",
        "sid": 4,
    },
    {
        "i": 808,
        "name": "Molung Hydropower Company Ltd",
        "symbol": "MHCL",
        "sid": 7,
    },
    {
        "i": 767,
        "name": "Mandakini Hydropower Limited",
        "symbol": "MHL",
        "sid": 7,
    },
    {
        "i": 164,
        "name": "Mountain Hydro Nepal Limited",
        "symbol": "MHNL",
        "sid": 7,
    },
    {
        "i": 849,
        "name": "Muktinath Krishi Company Ltd.",
        "symbol": "MKCL",
        "sid": 14,
    },
    {
        "i": 803,
        "name": "Maya Khola Hydropower Company Limited",
        "symbol": "MKHC",
        "sid": 7,
    },
    {
        "i": 829,
        "name": "Mai Khola Hydropower Limited",
        "symbol": "MKHL",
        "sid": 7,
    },
    {
        "i": 579,
        "name": "Mailung Khola Jal Vidhyut Company Limited",
        "symbol": "MKJC",
        "sid": 7,
    },
    {
        "i": 681,
        "name": "Manakamana Smart Laghubitta Bittiya Sanstha Limited",
        "symbol": "MKLB",
        "sid": 11,
    },
    {
        "i": 727,
        "name": "Manakamana Smart Laghubitta Bittiya Sanstha Limited Promoter",
        "symbol": "MKLBP",
        "sid": 11,
    },
    {
        "i": 301,
        "name": "Mithila LaghuBitta Bittiya Sanstha Limited",
        "symbol": "MLBBL",
        "sid": 11,
    },
    {
        "i": 302,
        "name": "Mithila LaghuBitta Bittiya Sanstha Limited Promoter Share",
        "symbol": "MLBBLP",
        "sid": 11,
    },
    {
        "i": 79,
        "name": "Mahalaxmi Bikas Bank Ltd.",
        "symbol": "MLBL",
        "sid": 3,
    },
    {
        "i": 80,
        "name": "Mahalaxmi Bikas Bank Limited Promoter Share",
        "symbol": "MLBLPO",
        "sid": 3,
    },
    {
        "i": 723,
        "name": "Manushi Laghubitta Bittiya Sanstha Limited",
        "symbol": "MLBS",
        "sid": 11,
    },
    {
        "i": 682,
        "name": "Mahila Laghubitta Bittiya Sanstha Limited",
        "symbol": "MLBSL",
        "sid": 11,
    },
    {
        "i": 684,
        "name": "Mahila Laghubitta Bittiya Sanstha Limited Promoter share",
        "symbol": "MLBSLP",
        "sid": 11,
    },
    {
        "i": 921,
        "name": "Manushi Laghubitta Bittiya Sanstha Limited Promoter Share",
        "symbol": "MLBSP",
        "sid": 11,
    },
    {
        "i": 299,
        "name": "Mirmire Laghubitta Bittiya Sanstha Limited",
        "symbol": "MMFDB",
        "sid": 11,
    },
    {
        "i": 300,
        "name": "Mirmire Laghubitta Bittiya Sanstha Limited Promoter Share",
        "symbol": "MMFDBP",
        "sid": 11,
    },
    {
        "i": 864,
        "name": "Mathillo Mailun Khola Jalvidhyut Limited",
        "symbol": "MMKJL",
        "sid": 7,
    },
    {
        "i": 83,
        "name": "Muktinath Bikas Bank Ltd.",
        "symbol": "MNBBL",
        "sid": 3,
    },
    {
        "i": 84,
        "name": "Muktinath Bikas Bank Limited Promoter Share",
        "symbol": "MNBBLP",
        "sid": 3,
    },
    {
        "i": 129,
        "name": "Multipurpose Finance Limited",
        "symbol": "MPFL",
        "sid": 4,
    },
    {
        "i": 128,
        "name": "Multipurpose Finance Company Limited Promoter Share",
        "symbol": "MPFLPO",
        "sid": 4,
    },
    {
        "i": 862,
        "name": "Mid- Solu Hydropower Ltd",
        "symbol": "MSHL",
        "sid": 7,
    },
    {
        "i": 295,
        "name": "Mahuli Laghubitta Bittiya Sanstha Ltd.",
        "symbol": "MSLB",
        "sid": 11,
    },
    {
        "i": 296,
        "name": "Mahuli Samudayik Laghubitta Bittiya Sanstha Limited Promoter Share",
        "symbol": "MSLBP",
        "sid": 11,
    },
    {
        "i": 410,
        "name": "Narayani Development Bank Limited",
        "symbol": "NABBC",
        "sid": 3,
    },
    {
        "i": 879,
        "name": "Narayani Development Bank Limited Promoter Share",
        "symbol": "NABBCP",
        "sid": 3,
    },
    {
        "i": 26,
        "name": "Nabil Bank Limited",
        "symbol": "NABIL",
        "sid": 1,
    },
    {
        "i": 27,
        "name": "Nabil Bank Limited Promoter Share",
        "symbol": "NABILP",
        "sid": 1,
    },
    {
        "i": 303,
        "name": "Nadep Laghubittiya Bittiya Sanstha Ltd.",
        "symbol": "NADEP",
        "sid": 11,
    },
    {
        "i": 304,
        "name": "Nadep Laghubitta bittiya Sanstha Limited Promoter Share",
        "symbol": "NADEPP",
        "sid": 11,
    },
    {
        "i": 28,
        "name": "Nepal Bangladesh Bank Limited",
        "symbol": "NBB",
        "sid": 1,
    },
    {
        "i": 29,
        "name": "Nepal Bangladesh Bank Limited Promoter Share",
        "symbol": "NBBPO",
        "sid": 1,
    },
    {
        "i": 30,
        "name": "Nepal Bank Limited",
        "symbol": "NBL",
        "sid": 1,
    },
    {
        "i": 31,
        "name": "Nepal Credit And Commercial Bank Limited",
        "symbol": "NCCB",
        "sid": 1,
    },
    {
        "i": 32,
        "name": "Nepal Credit And Commerce Bank Limited Promoter Share",
        "symbol": "NCCBPO",
        "sid": 1,
    },
    {
        "i": 706,
        "name": "Nesdo Sambridha Laghubitta Bittiya Sanstha Limited",
        "symbol": "NESDO",
        "sid": 11,
    },
    {
        "i": 920,
        "name": "Nesdo Sambridha Laghubitta Bittiya Sanstha Limited Promoter Share",
        "symbol": "NESDOP",
        "sid": 11,
    },
    {
        "i": 130,
        "name": "Nepal Finance Ltd.",
        "symbol": "NFS",
        "sid": 4,
    },
    {
        "i": 131,
        "name": "Nepal Finance Limited Promoter Share",
        "symbol": "NFSPO",
        "sid": 4,
    },
    {
        "i": 167,
        "name": "Ngadi Group Power Ltd.",
        "symbol": "NGPL",
        "sid": 7,
    },
    {
        "i": 166,
        "name": "Nepal Hydro Developers Ltd.",
        "symbol": "NHDL",
        "sid": 7,
    },
    {
        "i": 165,
        "name": "National Hydro Power Company Limited",
        "symbol": "NHPC",
        "sid": 7,
    },
    {
        "i": 33,
        "name": "Nepal Investment Bank Limited",
        "symbol": "NIB",
        "sid": 1,
    },
    {
        "i": 37,
        "name": "NIC Asia Bank Ltd.",
        "symbol": "NICA",
        "sid": 1,
    },
    {
        "i": 38,
        "name": "NIC Asia Bank Limited Promoter Share",
        "symbol": "NICAP",
        "sid": 1,
    },
    {
        "i": 209,
        "name": "Nepal Insurance Co. Ltd.",
        "symbol": "NICL",
        "sid": 13,
    },
    {
        "i": 582,
        "name": "NIC ASIA Laghubitta Bittiya Sanstha Limited",
        "symbol": "NICLBSL",
        "sid": 11,
    },
    {
        "i": 922,
        "name": "NIC ASIA Laghubitta Bittiya Sanstha Limited Promoter Share",
        "symbol": "NICLBSLP",
        "sid": 11,
    },
    {
        "i": 210,
        "name": "Nepal Insurance Company Limited Promoter Share",
        "symbol": "NICLPO",
        "sid": 13,
    },
    {
        "i": 612,
        "name": "Nepal Infrastructure Bank Limited",
        "symbol": "NIFRA",
        "sid": 8,
    },
    {
        "i": 675,
        "name": "Nepal Infrastructure Bank- Promotor",
        "symbol": "NIFRAP",
        "sid": 8,
    },
    {
        "i": 208,
        "name": "Neco Insurance Co. Ltd.",
        "symbol": "NIL",
        "sid": 13,
    },
    {
        "i": 207,
        "name": "Neco Insurance Company Limited Promoter Share",
        "symbol": "NILPO",
        "sid": 13,
    },
    {
        "i": 770,
        "name": "Nepal Investment Mega Bank Limited",
        "symbol": "NIMB",
        "sid": 1,
    },
    {
        "i": 34,
        "name": "Nepal Investment Mega Bank Limited Promoter Share",
        "symbol": "NIMBPO",
        "sid": 1,
    },
    {
        "i": 315,
        "name": "Nerude Laghubitta Bittiya Sanstha Limited",
        "symbol": "NLBBL",
        "sid": 11,
    },
    {
        "i": 316,
        "name": "Nerude Laghubitta Bittiya Sanstha Limited Promoter Share",
        "symbol": "NLBBLP",
        "sid": 11,
    },
    {
        "i": 211,
        "name": "NLG Insurance Company Ltd.",
        "symbol": "NLG",
        "sid": 13,
    },
    {
        "i": 212,
        "name": "NLG Insurance Company Limited Promoter Share",
        "symbol": "NLGPO",
        "sid": 13,
    },
    {
        "i": 249,
        "name": "Nepal Life Insurance Co. Ltd.",
        "symbol": "NLIC",
        "sid": 9,
    },
    {
        "i": 247,
        "name": "National Life Insurance Co. Ltd.",
        "symbol": "NLICL",
        "sid": 9,
    },
    {
        "i": 248,
        "name": "National Life Insurance Company Limited Promoter Share",
        "symbol": "NLICLP",
        "sid": 9,
    },
    {
        "i": 250,
        "name": "Nepal Life Insurance Company Limited Promoter Share",
        "symbol": "NLICP",
        "sid": 9,
    },
    {
        "i": 237,
        "name": "Nepal Lube Oil Limited",
        "symbol": "NLO",
        "sid": 10,
    },
    {
        "i": 39,
        "name": "NMB Bank Limited",
        "symbol": "NMB",
        "sid": 1,
    },
    {
        "i": 320,
        "name": "NMB Laghubitta Bittiya Sanstha Ltd.",
        "symbol": "NMBMF",
        "sid": 11,
    },
    {
        "i": 319,
        "name": "NMB Laghubitta Bittiya Sanstha Limited Promoter Share",
        "symbol": "NMBMFP",
        "sid": 11,
    },
    {
        "i": 40,
        "name": "NMB Bank Limited Promoter Share",
        "symbol": "NMBPO",
        "sid": 1,
    },
    {
        "i": 308,
        "name": "National Laghubitta  Bittiya Sanstha Ltd.",
        "symbol": "NMFBS",
        "sid": 11,
    },
    {
        "i": 307,
        "name": "National Laghubitta Bittiya Sanstha Limited Promoter Share",
        "symbol": "NMFBSP",
        "sid": 11,
    },
    {
        "i": 907,
        "name": "Nerude Mirmire Laghubitta Bittiya Sanstha Limited",
        "symbol": "NMLBBL",
        "sid": 11,
    },
    {
        "i": 935,
        "name": "Nerude Mirmire Laghubitta Bittiya Sasntha Limited- Promoter Share",
        "symbol": "NMLBBLP",
        "sid": 11,
    },
    {
        "i": 571,
        "name": "Nepal Reinsurance Company Limited",
        "symbol": "NRIC",
        "sid": 14,
    },
    {
        "i": 928,
        "name": "Nepal Reinsurance Company Limited Promoter Share",
        "symbol": "NRICP",
        "sid": 14,
    },
    {
        "i": 867,
        "name": "Nepal Republic Media Limited",
        "symbol": "NRM",
        "sid": 14,
    },
    {
        "i": 570,
        "name": "NRN Infrastructure and Development Limited",
        "symbol": "NRN",
        "sid": 8,
    },
    {
        "i": 604,
        "name": "Naya Sarathi Laghubitta Bittiya Sanstha Limited",
        "symbol": "NSLB",
        "sid": 11,
    },
    {
        "i": 658,
        "name": "Naya Sarathi Nepal Laghubitta Bittiya Sanstha Limited Promoter Share",
        "symbol": "NSLBP",
        "sid": 11,
    },
    {
        "i": 231,
        "name": "Nepal Doorsanchar Company Limited",
        "symbol": "NTC",
        "sid": 14,
    },
    {
        "i": 317,
        "name": "Nirdhan Utthan Laghubitta Bittiya Sanstha Limited",
        "symbol": "NUBL",
        "sid": 11,
    },
    {
        "i": 318,
        "name": "Nirdhan Utthan Laghubitta Bittiya Sanstha Limited Promoter Share",
        "symbol": "NUBLPO",
        "sid": 11,
    },
    {
        "i": 853,
        "name": "Nepal Warehousing Company Ltd",
        "symbol": "NWCL",
        "sid": 14,
    },
    {
        "i": 726,
        "name": "Nyadi Hydropower Limited",
        "symbol": "NYADI",
        "sid": 7,
    },
    {
        "i": 146,
        "name": "Oriental Hotels Limited",
        "symbol": "OHL",
        "sid": 6,
    },
    {
        "i": 43,
        "name": "Prime Commercial Bank Limited",
        "symbol": "PCBL",
        "sid": 1,
    },
    {
        "i": 44,
        "name": "Prime Commercial Bank Limited Promoter Share",
        "symbol": "PCBLP",
        "sid": 1,
    },
    {
        "i": 132,
        "name": "Pokhara Finance Ltd.",
        "symbol": "PFL",
        "sid": 4,
    },
    {
        "i": 133,
        "name": "Pokhara Finance Limited Promoter Share",
        "symbol": "PFLPO",
        "sid": 4,
    },
    {
        "i": 793,
        "name": "Peoples Hydropower Company Limited",
        "symbol": "PHCL",
        "sid": 7,
    },
    {
        "i": 215,
        "name": "Premier Insurance Co. Ltd.",
        "symbol": "PIC",
        "sid": 13,
    },
    {
        "i": 217,
        "name": "Prudential Insurance Co. Ltd.",
        "symbol": "PICL",
        "sid": 13,
    },
    {
        "i": 218,
        "name": "Prudential Insurance Company Limited Promoter Share",
        "symbol": "PICLPO",
        "sid": 13,
    },
    {
        "i": 216,
        "name": "Premier Insurance Company Limited Promoter Share",
        "symbol": "PICPO",
        "sid": 13,
    },
    {
        "i": 605,
        "name": "Prabhu Life Insurance",
        "symbol": "PLI",
        "sid": 9,
    },
    {
        "i": 251,
        "name": "Prime Life Insurance Company Limited",
        "symbol": "PLIC",
        "sid": 9,
    },
    {
        "i": 252,
        "name": "Prime Life Insurance Company Limited Promoter Share",
        "symbol": "PLICPO",
        "sid": 9,
    },
    {
        "i": 168,
        "name": "Panchakanya Mai Hydropower Ltd",
        "symbol": "PMHPL",
        "sid": 7,
    },
    {
        "i": 886,
        "name": "Prabhu Mahalaxmi Life Insurance Limited",
        "symbol": "PMLI",
        "sid": 9,
    },
    {
        "i": 926,
        "name": "Prabhu Mahalaxmi Life Insurance Company Limited- Promoter Share",
        "symbol": "PMLIP",
        "sid": 9,
    },
    {
        "i": 169,
        "name": "Panchthar Power Company Limited",
        "symbol": "PPCL",
        "sid": 7,
    },
    {
        "i": 769,
        "name": "Peoples Power Limited",
        "symbol": "PPL",
        "sid": 7,
    },
    {
        "i": 213,
        "name": "Prabhu Insurance Ltd.",
        "symbol": "PRIN",
        "sid": 13,
    },
    {
        "i": 214,
        "name": "Prabhu Insurance Limited Promoter Share",
        "symbol": "PRINPO",
        "sid": 13,
    },
    {
        "i": 134,
        "name": "Progressive Finance Limited",
        "symbol": "PROFL",
        "sid": 4,
    },
    {
        "i": 135,
        "name": "Progressive Finance Limited Promoter Share",
        "symbol": "PROFLP",
        "sid": 4,
    },
    {
        "i": 41,
        "name": "Prabhu Bank Limited",
        "symbol": "PRVU",
        "sid": 1,
    },
    {
        "i": 42,
        "name": "Prabhu Bank Limited Promoter Share",
        "symbol": "PRVUPO",
        "sid": 1,
    },
    {
        "i": 170,
        "name": "Radhi Bidyut Company Ltd",
        "symbol": "RADHI",
        "sid": 7,
    },
    {
        "i": 840,
        "name": "Rawa Energy Development Limited",
        "symbol": "RAWA",
        "sid": 7,
    },
    {
        "i": 219,
        "name": "Rastriya Beema Company Limited",
        "symbol": "RBCL",
        "sid": 13,
    },
    {
        "i": 220,
        "name": "Rastriya Beema Company Limited Promoter Share",
        "symbol": "RBCLPO",
        "sid": 13,
    },
    {
        "i": 750,
        "name": "River Falls Power Limited",
        "symbol": "RFPL",
        "sid": 7,
    },
    {
        "i": 762,
        "name": "Rapti Hydro & General Construction Limited",
        "symbol": "RHGCL",
        "sid": 7,
    },
    {
        "i": 172,
        "name": "Rasuwagadhi Hydropower Company Limited",
        "symbol": "RHPL",
        "sid": 7,
    },
    {
        "i": 789,
        "name": "Ridi Power Company Limited",
        "symbol": "RIDI",
        "sid": 7,
    },
    {
        "i": 136,
        "name": "Reliance Finance Ltd.",
        "symbol": "RLFL",
        "sid": 4,
    },
    {
        "i": 137,
        "name": "Reliance Finance Limited Promoter Share",
        "symbol": "RLFLPO",
        "sid": 4,
    },
    {
        "i": 583,
        "name": "Reliance Life Insurance Limited",
        "symbol": "RLI",
        "sid": 9,
    },
    {
        "i": 611,
        "name": "Reliance Life Insurance Limited Promotor Share",
        "symbol": "RLIP",
        "sid": 9,
    },
    {
        "i": 321,
        "name": "RMDC Laghubitta Bittiya Sanstha Ltd.",
        "symbol": "RMDC",
        "sid": 11,
    },
    {
        "i": 322,
        "name": "RMDC Laghubitta Bittiya Sanstha Limited Promoter Share",
        "symbol": "RMDCPO",
        "sid": 11,
    },
    {
        "i": 851,
        "name": "Reliable Nepal Life Insurance Ltd.",
        "symbol": "RNLI",
        "sid": 9,
    },
    {
        "i": 900,
        "name": "Reliable Nepal Life Insurance Ltd Promoter Share",
        "symbol": "RNLIP",
        "sid": 9,
    },
    {
        "i": 171,
        "name": "Rairang Hydropower Development Company Ltd.",
        "symbol": "RRHP",
        "sid": 7,
    },
    {
        "i": 323,
        "name": "RSDC Laghubitta Bittiya Sanstha Ltd.",
        "symbol": "RSDC",
        "sid": 11,
    },
    {
        "i": 324,
        "name": "RSDC Laghubitta Bittiya Sanstha Limited Promoter Share",
        "symbol": "RSDCP",
        "sid": 11,
    },
    {
        "i": 744,
        "name": "Rastra Utthan Laghubitta Bittiya Sanstha Ltd",
        "symbol": "RULB",
        "sid": 11,
    },
    {
        "i": 746,
        "name": "Rastra Utthan Laghubitta Bittiya Sanstha Ltd Promoter Share",
        "symbol": "RULBP",
        "sid": 11,
    },
    {
        "i": 670,
        "name": "Ru Ru Jalbidhyut Pariyojana Limited",
        "symbol": "RURU",
        "sid": 7,
    },
    {
        "i": 325,
        "name": "Sabaiko Laghubitta Bittiya Sanstha Limited",
        "symbol": "SABSL",
        "sid": 11,
    },
    {
        "i": 326,
        "name": "Sabaiko Laghubitta Bittiya Sanstha Limited Promoter Share",
        "symbol": "SABSLPO",
        "sid": 11,
    },
    {
        "i": 96,
        "name": "Shangrila Development Bank Ltd.",
        "symbol": "SADBL",
        "sid": 3,
    },
    {
        "i": 97,
        "name": "Shangri-la Development Bank Limited Promoter Share",
        "symbol": "SADBLP",
        "sid": 3,
    },
    {
        "i": 724,
        "name": "Sahas Urja Ltd.",
        "symbol": "SAHAS",
        "sid": 7,
    },
    {
        "i": 834,
        "name": "Sagarmatha Lumbini Insurance Company Limited",
        "symbol": "SALICO",
        "sid": 13,
    },
    {
        "i": 877,
        "name": "Sagarmatha Lumbini Insurance Company Limited Promoter Share",
        "symbol": "SALICOPO",
        "sid": 13,
    },
    {
        "i": 584,
        "name": "Samaj Laghubitta Bittiya Sanstha Limited",
        "symbol": "SAMAJ",
        "sid": 11,
    },
    {
        "i": 891,
        "name": "Samaj Laghubitta Bittiya Sanstha Limited Promoter Share",
        "symbol": "SAMAJP",
        "sid": 11,
    },
    {
        "i": 45,
        "name": "Sanima Bank Limited",
        "symbol": "SANIMA",
        "sid": 1,
    },
    {
        "i": 569,
        "name": "Saptakoshi Development Bank Ltd",
        "symbol": "SAPDBL",
        "sid": 3,
    },
    {
        "i": 95,
        "name": "Saptakoshi Development Bank Limited Promoter Share",
        "symbol": "SAPDBLP",
        "sid": 3,
    },
    {
        "i": 661,
        "name": "Sarbottam Cement Limited",
        "symbol": "SARBTM",
        "sid": 10,
    },
    {
        "i": 46,
        "name": "Sanima Bank Limited Promoter Share",
        "symbol": "SBBLPO",
        "sid": 1,
    },
    {
        "i": 36,
        "name": "Nepal SBI Bank Limited",
        "symbol": "SBI",
        "sid": 1,
    },
    {
        "i": 35,
        "name": "Nepal SBI Bank Limited Promoter Share",
        "symbol": "SBIPO",
        "sid": 1,
    },
    {
        "i": 47,
        "name": "Siddhartha Bank Limited",
        "symbol": "SBL",
        "sid": 1,
    },
    {
        "i": 48,
        "name": "Siddhartha Bank Limited Promoter Share",
        "symbol": "SBLPO",
        "sid": 1,
    },
    {
        "i": 49,
        "name": "Standard Chartered Bank Limited",
        "symbol": "SCB",
        "sid": 1,
    },
    {
        "i": 50,
        "name": "Standard Chartered Bank Nepal Limited Promoter Share",
        "symbol": "SCBPO",
        "sid": 1,
    },
    {
        "i": 580,
        "name": "Sadhana Laghubitta Bittiya Sanstha Limited",
        "symbol": "SDLBSL",
        "sid": 11,
    },
    {
        "i": 924,
        "name": "Sadhana Laghubitta Bittiya Sanstha Limited Promoter Share",
        "symbol": "SDLBSLP",
        "sid": 11,
    },
    {
        "i": 138,
        "name": "Samriddhi Finance Company Limited",
        "symbol": "SFCL",
        "sid": 4,
    },
    {
        "i": 139,
        "name": "Samriddhi Finance Company Limited Promoter Share",
        "symbol": "SFCLP",
        "sid": 4,
    },
    {
        "i": 763,
        "name": "Swet Ganga Hydropower & Construction Ltd",
        "symbol": "SGHC",
        "sid": 7,
    },
    {
        "i": 585,
        "name": "Sanima General Insurance Company Limited",
        "symbol": "SGI",
        "sid": 13,
    },
    {
        "i": 826,
        "name": "Sanima GIC Insurance Limited",
        "symbol": "SGIC",
        "sid": 13,
    },
    {
        "i": 827,
        "name": "Sanima GIC Insurance Limited- Promoter Share",
        "symbol": "SGICP",
        "sid": 13,
    },
    {
        "i": 816,
        "name": "Sanima General Insurance Company Limited Promoter Share",
        "symbol": "SGIP",
        "sid": 13,
    },
    {
        "i": 615,
        "name": "Singati Hydro Energy Limited",
        "symbol": "SHEL",
        "sid": 7,
    },
    {
        "i": 98,
        "name": "Shine Resunga Development Bank Ltd.",
        "symbol": "SHINE",
        "sid": 3,
    },
    {
        "i": 99,
        "name": "Shine Resunga Development Bank Limited Promoter Share",
        "symbol": "SHINEP",
        "sid": 3,
    },
    {
        "i": 238,
        "name": "Shivam Cement Ltd.",
        "symbol": "SHIVM",
        "sid": 10,
    },
    {
        "i": 147,
        "name": "Soaltee Hotel Limited",
        "symbol": "SHL",
        "sid": 6,
    },
    {
        "i": 666,
        "name": "Shrijanshil Laghubitta Bittiya Sanstha Limited",
        "symbol": "SHLB",
        "sid": 11,
    },
    {
        "i": 925,
        "name": "Shrijanshil Laghubitta Bittiya Sanstha Limited Promoter Share",
        "symbol": "SHLBP",
        "sid": 11,
    },
    {
        "i": 174,
        "name": "Sanima Mai Hydropower Ltd.",
        "symbol": "SHPC",
        "sid": 7,
    },
    {
        "i": 221,
        "name": "Sagarmatha Insurance Co. Ltd.",
        "symbol": "SIC",
        "sid": 13,
    },
    {
        "i": 223,
        "name": "Shikhar Insurance Co. Ltd.",
        "symbol": "SICL",
        "sid": 13,
    },
    {
        "i": 224,
        "name": "Shikhar Insurance Company Limited Promoter Share",
        "symbol": "SICLPO",
        "sid": 13,
    },
    {
        "i": 222,
        "name": "Sagarmatha Insurance Company Limited Promoter Share",
        "symbol": "SICPO",
        "sid": 13,
    },
    {
        "i": 141,
        "name": "Shree Investment and Finance Co. Ltd.",
        "symbol": "SIFC",
        "sid": 4,
    },
    {
        "i": 140,
        "name": "Shree Investment and Finance Company Limited Promoter Share",
        "symbol": "SIFCPO",
        "sid": 4,
    },
    {
        "i": 778,
        "name": "Sikles Hydropower Limited",
        "symbol": "SIKLES",
        "sid": 7,
    },
    {
        "i": 225,
        "name": "Siddhartha Insurance Ltd.",
        "symbol": "SIL",
        "sid": 13,
    },
    {
        "i": 226,
        "name": "Siddhartha Insurance Limited Promoter Share",
        "symbol": "SILPO",
        "sid": 13,
    },
    {
        "i": 100,
        "name": "Sindhu Bikash Bank Ltd",
        "symbol": "SINDU",
        "sid": 3,
    },
    {
        "i": 101,
        "name": "Sindhu Bikash Bank Limited Promoter Share",
        "symbol": "SINDUP",
        "sid": 3,
    },
    {
        "i": 175,
        "name": "Sanjen Jalavidhyut Company Limited",
        "symbol": "SJCL",
        "sid": 7,
    },
    {
        "i": 807,
        "name": "Suryajyoti Life Insurance Company Limited",
        "symbol": "SJLIC",
        "sid": 9,
    },
    {
        "i": 923,
        "name": "Suryajyoti Life Insurance Company Limited- Promoter Share",
        "symbol": "SJLICP",
        "sid": 9,
    },
    {
        "i": 331,
        "name": "Sana Kisan Bikas Laghubitta Bittiya Sanstha Limited",
        "symbol": "SKBBL",
        "sid": 11,
    },
    {
        "i": 332,
        "name": "Sana Kisan Bikas Bank Limited Promoter Share",
        "symbol": "SKBBLP",
        "sid": 11,
    },
    {
        "i": 347,
        "name": "Swarojgar Laghubitta Bittiya Sanstha Limited",
        "symbol": "SLBBL",
        "sid": 11,
    },
    {
        "i": 348,
        "name": "Swarojgar Laghubitta Bittiya Sanstha Limited Promoter Share",
        "symbol": "SLBBLP",
        "sid": 11,
    },
    {
        "i": 329,
        "name": "Samudayik Laghubitta Bittiya Sanstha Limited",
        "symbol": "SLBSL",
        "sid": 11,
    },
    {
        "i": 330,
        "name": "Samudayik Laghubitta Bittiya Sanstha Limited Promoter Share",
        "symbol": "SLBSLPO",
        "sid": 11,
    },
    {
        "i": 586,
        "name": "Sanima Life Insurance Company Limited",
        "symbol": "SLI",
        "sid": 9,
    },
    {
        "i": 253,
        "name": "Surya Life Insurance Company Limited",
        "symbol": "SLICL",
        "sid": 9,
    },
    {
        "i": 254,
        "name": "Surya Life Insurance Company Limited Promoter Share",
        "symbol": "SLICLP",
        "sid": 9,
    },
    {
        "i": 327,
        "name": "Samata Gharelu Laghubitta Bittiya Sanstha Limited",
        "symbol": "SMATA",
        "sid": 11,
    },
    {
        "i": 328,
        "name": "Samata Laghubitta Bittiya Sanstha Limited Promoter Share",
        "symbol": "SMATAP",
        "sid": 11,
    },
    {
        "i": 337,
        "name": "Support Microfinance Bittiya Sanstha Ltd.",
        "symbol": "SMB",
        "sid": 11,
    },
    {
        "i": 338,
        "name": "Support Microfinance Bittiya Sanstha Limited Promoter Share",
        "symbol": "SMBPO",
        "sid": 11,
    },
    {
        "i": 343,
        "name": "Swabhimaan Laghubitta Bittiya Sanstha Limited",
        "symbol": "SMFBS",
        "sid": 11,
    },
    {
        "i": 344,
        "name": "Swabhimaan Laghubitta Bittiya Sanstha Limited Promoter Share",
        "symbol": "SMFBSP",
        "sid": 11,
    },
    {
        "i": 335,
        "name": "Summit Laghubitta Bittiya Sanstha Limited",
        "symbol": "SMFDB",
        "sid": 11,
    },
    {
        "i": 336,
        "name": "Summit Laghubitta Bittiya Sanstha Limited Promoter Share",
        "symbol": "SMFDBP",
        "sid": 11,
    },
    {
        "i": 802,
        "name": "Super Mai Hydropower Limited",
        "symbol": "SMH",
        "sid": 7,
    },
    {
        "i": 806,
        "name": "Super Madi Hydropower Limited",
        "symbol": "SMHL",
        "sid": 7,
    },
    {
        "i": 815,
        "name": "Sagarmatha Jalbidhyut Company Ltd",
        "symbol": "SMJC",
        "sid": 7,
    },
    {
        "i": 937,
        "name": "Sampada Laghubitta Bittiya Sanstha Limited",
        "symbol": "SMPDA",
        "sid": 11,
    },
    {
        "i": 941,
        "name": "Sampada Laghubitta Bittiya Sasntha Limited - Promoter Share",
        "symbol": "SMPDAP",
        "sid": 11,
    },
    {
        "i": 882,
        "name": "Sun Nepal Life Insurance Company Limited",
        "symbol": "SNLI",
        "sid": 9,
    },
    {
        "i": 850,
        "name": "Sonapur Minerals and Oil Ltd",
        "symbol": "SONA",
        "sid": 10,
    },
    {
        "i": 334,
        "name": "Sparsha Laghubitta Bittiya Sanstha Limited Promoter Share",
        "symbol": "SPARSPO",
        "sid": 11,
    },
    {
        "i": 719,
        "name": "Samling Power Company Limited",
        "symbol": "SPC",
        "sid": 7,
    },
    {
        "i": 176,
        "name": "Synergy Power Development Ltd.",
        "symbol": "SPDL",
        "sid": 7,
    },
    {
        "i": 679,
        "name": "Sayapatri Hydropower Limited",
        "symbol": "SPHL",
        "sid": 7,
    },
    {
        "i": 837,
        "name": "Siddhartha Premier Insurance Company Limited",
        "symbol": "SPIL",
        "sid": 13,
    },
    {
        "i": 929,
        "name": "Siddhartha Premier Insurance Limited- Promoter Share",
        "symbol": "SPILPO",
        "sid": 13,
    },
    {
        "i": 578,
        "name": "Shuvam Power Limited",
        "symbol": "SPL",
        "sid": 7,
    },
    {
        "i": 51,
        "name": "Sunrise Bank Limited",
        "symbol": "SRBL",
        "sid": 1,
    },
    {
        "i": 52,
        "name": "Sunrise Bank Limited Promoter Share",
        "symbol": "SRBLPO",
        "sid": 1,
    },
    {
        "i": 848,
        "name": "Sanima Reliance Life Insurance Limited",
        "symbol": "SRLI",
        "sid": 9,
    },
    {
        "i": 876,
        "name": "Sanima Reliance Life Insurance Limited Promoter Share",
        "symbol": "SRLIP",
        "sid": 9,
    },
    {
        "i": 576,
        "name": "Shiva Shree Hydropower Limited",
        "symbol": "SSHL",
        "sid": 7,
    },
    {
        "i": 233,
        "name": "Salt Trading Corporation",
        "symbol": "STC",
        "sid": 16,
    },
    {
        "i": 341,
        "name": "Swabalamban Laghubitta Bittiya Sanstha Limited",
        "symbol": "SWBBL",
        "sid": 11,
    },
    {
        "i": 342,
        "name": "Swabalamban Laghubitta Bittiya Sanstha Limited Promoter Share",
        "symbol": "SWBBLP",
        "sid": 11,
    },
    {
        "i": 757,
        "name": "Suryodaya Womi Laghubitta Bittiya Sanstha Limited",
        "symbol": "SWMF",
        "sid": 11,
    },
    {
        "i": 931,
        "name": "Suryodaya Womi Laghubitta Bittiya Sanstha Limited Promote Share",
        "symbol": "SWMFPO",
        "sid": 11,
    },
    {
        "i": 814,
        "name": "Sanima Middle Tamor Hydropower",
        "symbol": "TAMOR",
        "sid": 7,
    },
    {
        "i": 712,
        "name": "Tehrathum Power Company Limited",
        "symbol": "TPC",
        "sid": 7,
    },
    {
        "i": 148,
        "name": "Taragaon Regency Hotel Limited",
        "symbol": "TRH",
        "sid": 6,
    },
    {
        "i": 844,
        "name": "Three Star Hydropower Limited",
        "symbol": "TSHL",
        "sid": 7,
    },
    {
        "i": 575,
        "name": "Trishuli Jal Vidhyut Company Limited",
        "symbol": "TVCL",
        "sid": 7,
    },
    {
        "i": 880,
        "name": "United Ajod Insurance Limited",
        "symbol": "UAIL",
        "sid": 13,
    },
    {
        "i": 893,
        "name": "United Ajod Insurance Limited Promoter Share",
        "symbol": "UAILPO",
        "sid": 13,
    },
    {
        "i": 145,
        "name": "United Finance Limited Promoter Share",
        "symbol": "UFLPO",
        "sid": 4,
    },
    {
        "i": 758,
        "name": "Upper Hewakhola Hydropower Limited",
        "symbol": "UHEWA",
        "sid": 7,
    },
    {
        "i": 227,
        "name": "United Insurance Co. (Nepal) Ltd.",
        "symbol": "UIC",
        "sid": 13,
    },
    {
        "i": 228,
        "name": "United Insurance Company (Nepal) Limited Promoter Share",
        "symbol": "UICPO",
        "sid": 13,
    },
    {
        "i": 749,
        "name": "Upakar Laghubitta Bittiya Sanstha Ltd",
        "symbol": "ULBSL",
        "sid": 11,
    },
    {
        "i": 932,
        "name": "Upakar Laghubitta Bittiya Sanstha Ltd Promoter Share",
        "symbol": "ULBSLPO",
        "sid": 11,
    },
    {
        "i": 857,
        "name": "Upper Lohore Khola Hydropower Company Ltd.",
        "symbol": "ULHC",
        "sid": 7,
    },
    {
        "i": 704,
        "name": "Union Life Insurance Company Limited",
        "symbol": "ULI",
        "sid": 9,
    },
    {
        "i": 722,
        "name": "Union Life Insurance Company Limited Promoter Share",
        "symbol": "ULIP",
        "sid": 9,
    },
    {
        "i": 178,
        "name": "United Modi Hydropower Ltd.",
        "symbol": "UMHL",
        "sid": 7,
    },
    {
        "i": 606,
        "name": "United IDI Mardi and RB Hydropower Ltd",
        "symbol": "UMRH",
        "sid": 7,
    },
    {
        "i": 177,
        "name": "Union Hydropower Limited",
        "symbol": "UNHPL",
        "sid": 7,
    },
    {
        "i": 240,
        "name": "Unilever Nepal Limited",
        "symbol": "UNL",
        "sid": 10,
    },
    {
        "i": 736,
        "name": "Unique Nepal Laghubitta Bittiya Sanstha Limited",
        "symbol": "UNLB",
        "sid": 11,
    },
    {
        "i": 828,
        "name": "Unique Nepal Laghubitta Bittiya Sanstha Limited Promoter Share",
        "symbol": "UNLBP",
        "sid": 11,
    },
    {
        "i": 179,
        "name": "Universal Power Company Limited",
        "symbol": "UPCL",
        "sid": 7,
    },
    {
        "i": 180,
        "name": "Upper Tamakoshi Hydropower Ltd",
        "symbol": "UPPER",
        "sid": 7,
    },
    {
        "i": 755,
        "name": "Upper Solu Hydro Electric Company Limited",
        "symbol": "USHEC",
        "sid": 7,
    },
    {
        "i": 870,
        "name": "Upper Syange Hydropower Limited",
        "symbol": "USHL",
        "sid": 7,
    },
    {
        "i": 587,
        "name": "Unnati Sahakarya Laghubitta Bittiya Sanstha Limited",
        "symbol": "USLB",
        "sid": 11,
    },
    {
        "i": 934,
        "name": "Unnati Sahakarya Laghubitta Bittiya Sanstha Limited  Promoter Share",
        "symbol": "USLBP",
        "sid": 11,
    },
    {
        "i": 351,
        "name": "Vijaya laghubitta Bittiya Sanstha Ltd.",
        "symbol": "VLBS",
        "sid": 11,
    },
    {
        "i": 352,
        "name": "Vijaya laghubitta Bittiya Sanstha Limited Promoter Share",
        "symbol": "VLBSPO",
        "sid": 11,
    },
    {
        "i": 854,
        "name": "Vision Lumbini Urja Company Limited",
        "symbol": "VLUCL",
        "sid": 7,
    },
    {
        "i": 313,
        "name": "Wean Nepal Laghubitta Bittiya Sanstha Limited",
        "symbol": "WNLB",
        "sid": 11,
    },
    {
        "i": 933,
        "name": "Wean Nepal Laghubitta Bittiya Sanstha Limited Promoter Share",
        "symbol": "WNLBP",
        "sid": 11,
    },
    {
        "i": 353,
        "name": "Womi Microfinance Bittiya Sanstha Ltd.",
        "symbol": "WOMI",
        "sid": 11,
    },
    {
        "i": 846,
        "name": "Citizens Super 30 Mutual Fund",
        "symbol": "C30MF",
        "sid": 12,
    },
    {
        "i": 181,
        "name": "Citizens Mutual Fund -1",
        "symbol": "CMF1",
        "sid": 12,
    },
    {
        "i": 182,
        "name": "Citizens Mutual Fund 2",
        "symbol": "CMF2",
        "sid": 12,
    },
    {
        "i": 776,
        "name": "Global IME Balanced Fund - 1",
        "symbol": "GIBF1",
        "sid": 12,
    },
    {
        "i": 896,
        "name": "Himalayan 80-20",
        "symbol": "H8020",
        "sid": 12,
    },
    {
        "i": 759,
        "name": "Kumari Dhanabriddhi Yojana",
        "symbol": "KDBY",
        "sid": 12,
    },
    {
        "i": 694,
        "name": "Kumari Equity Fund",
        "symbol": "KEF",
        "sid": 12,
    },
    {
        "i": 835,
        "name": "Kumari Sunaulo Lagani Yojana",
        "symbol": "KSLY",
        "sid": 12,
    },
    {
        "i": 917,
        "name": "Kumari Sabal Yojana",
        "symbol": "KSY",
        "sid": 12,
    },
    {
        "i": 184,
        "name": "Laxmi Equity Fund",
        "symbol": "LEMF",
        "sid": 12,
    },
    {
        "i": 590,
        "name": "Laxmi Unnati Kosh",
        "symbol": "LUK",
        "sid": 12,
    },
    {
        "i": 185,
        "name": "Laxmi Value Fund-1",
        "symbol": "LVF1",
        "sid": 12,
    },
    {
        "i": 884,
        "name": "Laxmi Value Fund II",
        "symbol": "LVF2",
        "sid": 12,
    },
    {
        "i": 728,
        "name": "Mega Mutual Fund - 1",
        "symbol": "MMF1",
        "sid": 12,
    },
    {
        "i": 609,
        "name": "NIC Asia Dynamic Debt Fund",
        "symbol": "NADDF",
        "sid": 12,
    },
    {
        "i": 186,
        "name": "NABIL BALANCED FUND-2",
        "symbol": "NBF2",
        "sid": 12,
    },
    {
        "i": 732,
        "name": "Nabil Balanced Fund III",
        "symbol": "NBF3",
        "sid": 12,
    },
    {
        "i": 187,
        "name": "Nabil Equity Fund",
        "symbol": "NEF",
        "sid": 12,
    },
    {
        "i": 797,
        "name": "Nabil Flexi Cap Fund",
        "symbol": "NFCF",
        "sid": 12,
    },
    {
        "i": 810,
        "name": "NIBL Growth Fund",
        "symbol": "NIBLGF",
        "sid": 12,
    },
    {
        "i": 188,
        "name": "NIBL Pragati Fund",
        "symbol": "NIBLPF",
        "sid": 12,
    },
    {
        "i": 593,
        "name": "NIBL Sahabhagita Fund",
        "symbol": "NIBLSF",
        "sid": 12,
    },
    {
        "i": 915,
        "name": "NIBL Stable Fund",
        "symbol": "NIBLSTF",
        "sid": 12,
    },
    {
        "i": 189,
        "name": "NIBL Samriddhi Fund 1",
        "symbol": "NIBSF1",
        "sid": 12,
    },
    {
        "i": 693,
        "name": "NIBL Samriddhi Fund - II",
        "symbol": "NIBSF2",
        "sid": 12,
    },
    {
        "i": 190,
        "name": "NIC Asia Balanced Fund",
        "symbol": "NICBF",
        "sid": 12,
    },
    {
        "i": 760,
        "name": "NIC ASIA Flexi CAP Fund",
        "symbol": "NICFC",
        "sid": 12,
    },
    {
        "i": 191,
        "name": "NIC Asia Growth Fund",
        "symbol": "NICGF",
        "sid": 12,
    },
    {
        "i": 910,
        "name": "NIC Asia Growth Fund-2",
        "symbol": "NICGF2",
        "sid": 12,
    },
    {
        "i": 699,
        "name": "NIC Asia Select-30",
        "symbol": "NICSF",
        "sid": 12,
    },
    {
        "i": 589,
        "name": "NMB 50",
        "symbol": "NMB50",
        "sid": 12,
    },
    {
        "i": 192,
        "name": "NMB Hybrid Fund L-1",
        "symbol": "NMBHF1",
        "sid": 12,
    },
    {
        "i": 701,
        "name": "NMB Saral Bachat Fund - E (Open End)",
        "symbol": "NMBSBF",
        "sid": 12,
    },
    {
        "i": 785,
        "name": "NMB Sulav Investment Fund - II",
        "symbol": "NSIF2",
        "sid": 12,
    },
    {
        "i": 842,
        "name": "Prabhu Smart Fund",
        "symbol": "PRSF",
        "sid": 12,
    },
    {
        "i": 698,
        "name": "Prabhu Select Fund",
        "symbol": "PSF",
        "sid": 12,
    },
    {
        "i": 700,
        "name": "RBB Mutual Fund 1",
        "symbol": "RMF1",
        "sid": 12,
    },
    {
        "i": 845,
        "name": "RBB Mutual Fund 2",
        "symbol": "RMF2",
        "sid": 12,
    },
    {
        "i": 194,
        "name": "Sanima Equity Fund",
        "symbol": "SAEF",
        "sid": 12,
    },
    {
        "i": 794,
        "name": "Sanima Growth Fund",
        "symbol": "SAGF",
        "sid": 12,
    },
    {
        "i": 685,
        "name": "Sunrise Bluechip Fund",
        "symbol": "SBCF",
        "sid": 12,
    },
    {
        "i": 195,
        "name": "Siddhartha Equity Fund",
        "symbol": "SEF",
        "sid": 12,
    },
    {
        "i": 811,
        "name": "Sunrise Focused Equity Fund",
        "symbol": "SFEF",
        "sid": 12,
    },
    {
        "i": 198,
        "name": "Sunrise First Mutual Fund",
        "symbol": "SFMF",
        "sid": 12,
    },
    {
        "i": 519,
        "name": "Siddhartha Investment Growth Scheme-1",
        "symbol": "SIGS1",
        "sid": 12,
    },
    {
        "i": 197,
        "name": "Siddhartha Investment Growth Scheme - 2",
        "symbol": "SIGS2",
        "sid": 12,
    },
    {
        "i": 839,
        "name": "Siddhartha Investment Growth Scheme-3",
        "symbol": "SIGS3",
        "sid": 12,
    },
    {
        "i": 616,
        "name": "Sanima Large Cap Fund",
        "symbol": "SLCF",
        "sid": 12,
    },
    {
        "i": 782,
        "name": "Subha Laxmi Kosh",
        "symbol": "SLK",
        "sid": 12,
    },
    {
        "i": 711,
        "name": "Siddhartha Systematic Investment Scheme",
        "symbol": "SSIS",
        "sid": 12,
    },
    {
        "i": 911,
        "name": "4% AGRICULTURAL BOND",
        "symbol": "ADBLB",
        "sid": 2,
    },
    {
        "i": 715,
        "name": "4% Agricultural Bond (8 years)",
        "symbol": "ADBLB86",
        "sid": 2,
    },
    {
        "i": 938,
        "name": "4% Agricultural Bond (9 years)",
        "symbol": "ADBLB87",
        "sid": 2,
    },
    {
        "i": 665,
        "name": "10.35% Agricultural Bank Debenture 2083",
        "symbol": "ADBLD83 ",
        "sid": 2,
    },
    {
        "i": 608,
        "name": "8.5% BOK Debenture 2086",
        "symbol": "BOKD86",
        "sid": 2,
    },
    {
        "i": 784,
        "name": "10.50% BOK Debenture, 2086",
        "symbol": "BOKD86KA",
        "sid": 2,
    },
    {
        "i": 738,
        "name": "Civil Bank Debenture 2088",
        "symbol": "CBLD88",
        "sid": 2,
    },
    {
        "i": 753,
        "name": "10.50% Century Debenture 2088",
        "symbol": "CCBD88",
        "sid": 2,
    },
    {
        "i": 597,
        "name": "10.25% Citizens Bank Debenture 2086",
        "symbol": "CIZBD86",
        "sid": 2,
    },
    {
        "i": 902,
        "name": "10% Citizens Bank Debenture 2090",
        "symbol": "CIZBD90",
        "sid": 2,
    },
    {
        "i": 781,
        "name": "10.50% Everest Bank Rinpatra, 2085",
        "symbol": "EBLD85",
        "sid": 2,
    },
    {
        "i": 740,
        "name": "8.5% Everest Bank Debenture",
        "symbol": "EBLD86",
        "sid": 2,
    },
    {
        "i": 800,
        "name": "5.5% Everest Bank Ltd Urja Rinpatra 2089",
        "symbol": "EBLEB89",
        "sid": 2,
    },
    {
        "i": 737,
        "name": "8.75% Garima Debenture 2085",
        "symbol": "GBBD85",
        "sid": 2,
    },
    {
        "i": 820,
        "name": "11.25% Global IME Bank Debenture 2084/85.",
        "symbol": "GBILD84/85",
        "sid": 2,
    },
    {
        "i": 686,
        "name": "8.5% Global IME Bank Ltd. Debenture 2086/87",
        "symbol": "GBILD86/87",
        "sid": 2,
    },
    {
        "i": 676,
        "name": "12% Goodwill Finance Limited Debenture 2083",
        "symbol": "GWFD83",
        "sid": 2,
    },
    {
        "i": 592,
        "name": "10% Himalayan Bank Debenture 2083",
        "symbol": "HBLD83",
        "sid": 2,
    },
    {
        "i": 790,
        "name": "10.50% Himalayan Bank Limited 2086.",
        "symbol": "HBLD86",
        "sid": 2,
    },
    {
        "i": 674,
        "name": "12% ICFC Finance Limited Debenture 2083",
        "symbol": "ICFCD83",
        "sid": 2,
    },
    {
        "i": 690,
        "name": "9% Jyoti Bikas Bank Bond 2087",
        "symbol": "JBBD87",
        "sid": 2,
    },
    {
        "i": 598,
        "name": "10.25% KBL Debenture 2086",
        "symbol": "KBLD86",
        "sid": 2,
    },
    {
        "i": 791,
        "name": "11% KBL Debenture 2089",
        "symbol": "KBLD89",
        "sid": 2,
    },
    {
        "i": 904,
        "name": "10% KBL Debenture 2090",
        "symbol": "KBLD90",
        "sid": 2,
    },
    {
        "i": 672,
        "name": "9% KSBBL Debenture 2087",
        "symbol": "KSBBLD87",
        "sid": 2,
    },
    {
        "i": 878,
        "name": "11% LBBL Debenture 2089",
        "symbol": "LBBLD89",
        "sid": 2,
    },
    {
        "i": 667,
        "name": "10% Laxmi Bank Debenture 2086",
        "symbol": "LBLD86",
        "sid": 2,
    },
    {
        "i": 713,
        "name": "8.5% Laxmi Bank Debenture 2088",
        "symbol": "LBLD88",
        "sid": 2,
    },
    {
        "i": 683,
        "name": "10.25% Machhapuchhre Bank Debenture 2085",
        "symbol": "MBLD2085",
        "sid": 2,
    },
    {
        "i": 714,
        "name": "8.5% Machhapuchchhre Debenture 2087",
        "symbol": "MBLD87",
        "sid": 2,
    },
    {
        "i": 660,
        "name": "9.5% Manjushree Finance Ltd. Debenture 2085",
        "symbol": "MFLD85",
        "sid": 2,
    },
    {
        "i": 843,
        "name": "11% Mahalaxmi Debenture-2089",
        "symbol": "MLBLD89",
        "sid": 2,
    },
    {
        "i": 914,
        "name": "9% Nabil Debenture 2087",
        "symbol": "NABILD87",
        "sid": 2,
    },
    {
        "i": 599,
        "name": "10.25% NBBL Debenture 2085",
        "symbol": "NBBD2085",
        "sid": 2,
    },
    {
        "i": 594,
        "name": "10% Nabil Debenture 2082",
        "symbol": "NBLD82",
        "sid": 2,
    },
    {
        "i": 718,
        "name": "8% Nabil Bank Debenture 2085",
        "symbol": "NBLD85",
        "sid": 2,
    },
    {
        "i": 663,
        "name": "8.5% Nepal Bank Debeture 2087",
        "symbol": "NBLD87",
        "sid": 2,
    },
    {
        "i": 689,
        "name": "9.5% NCC Debenture 2086",
        "symbol": "NCCD86",
        "sid": 2,
    },
    {
        "i": 600,
        "name": "10.5 % Nepal Investment Debenture 2082",
        "symbol": "NIBD2082",
        "sid": 2,
    },
    {
        "i": 617,
        "name": "8.5% Nepal Investment Bank Bond 2084",
        "symbol": "NIBD84",
        "sid": 2,
    },
    {
        "i": 602,
        "name": "9% NIC Asia Debenture 2081/82",
        "symbol": "NICAD8182",
        "sid": 2,
    },
    {
        "i": 363,
        "name": "11% NIC Asia Debenture 082/83",
        "symbol": "NICAD8283",
        "sid": 2,
    },
    {
        "i": 367,
        "name": "10% NIC Asia Debenture 2085/86",
        "symbol": "NICAD85/86",
        "sid": 2,
    },
    {
        "i": 359,
        "name": "10.25% NIC Asia Debenture 2083/84",
        "symbol": "NICD83/84",
        "sid": 2,
    },
    {
        "i": 710,
        "name": "8.5% NIC Asia Debenture 2088",
        "symbol": "NICD88",
        "sid": 2,
    },
    {
        "i": 805,
        "name": "7% NIFRA Urja Rinpatra 2085/86",
        "symbol": "NIFRAUR85/86",
        "sid": 2,
    },
    {
        "i": 918,
        "name": "10% NIMB Debenture 2090",
        "symbol": "NIMBD90",
        "sid": 2,
    },
    {
        "i": 356,
        "name": "10% NMB DEBENTURE 2085",
        "symbol": "NMBD2085",
        "sid": 2,
    },
    {
        "i": 697,
        "name": "NMB Debenture 8.50% - 2087/88",
        "symbol": "NMBD87/88",
        "sid": 2,
    },
    {
        "i": 836,
        "name": "NMB Debenture 10.75%-2089/90",
        "symbol": "NMBD89/90",
        "sid": 2,
    },
    {
        "i": 662,
        "name": "4% NMB Energy Bond 2092/93",
        "symbol": "NMBEB2092/93",
        "sid": 2,
    },
    {
        "i": 754,
        "name": "NMB Urja Rinpatra (Energy Bond II) 4% 2093/94",
        "symbol": "NMBUR93/94",
        "sid": 2,
    },
    {
        "i": 768,
        "name": "10.15% Prime Debenture 2084",
        "symbol": "PBD84",
        "sid": 2,
    },
    {
        "i": 678,
        "name": "8.75% Prime Debenture 2085",
        "symbol": "PBD85",
        "sid": 2,
    },
    {
        "i": 748,
        "name": "10% Prime Debenture 2088",
        "symbol": "PBD88",
        "sid": 2,
    },
    {
        "i": 596,
        "name": "10% Prabhu Bank Debenture 2084",
        "symbol": "PBLD84",
        "sid": 2,
    },
    {
        "i": 366,
        "name": "10.25% Prabhu Bank Debenture 2086",
        "symbol": "PBLD86",
        "sid": 2,
    },
    {
        "i": 702,
        "name": "8.5% Prabhu Bank Debenture 2087",
        "symbol": "PBLD87",
        "sid": 2,
    },
    {
        "i": 703,
        "name": "8.5% RBBL Debenture 2083",
        "symbol": "RBBD83",
        "sid": 2,
    },
    {
        "i": 368,
        "name": "10% Sanima Bank Limited Debenture",
        "symbol": "SAND2085",
        "sid": 2,
    },
    {
        "i": 614,
        "name": "8.5% Sanima Debenture 2087",
        "symbol": "SBD87",
        "sid": 2,
    },
    {
        "i": 773,
        "name": "10.25% Sanima Debenture 2089",
        "symbol": "SBD89",
        "sid": 2,
    },
    {
        "i": 595,
        "name": "10% Nepal SBI Bank Debenture 2086",
        "symbol": "SBIBD86",
        "sid": 2,
    },
    {
        "i": 777,
        "name": "10.25% Nepal SBI Bank Debenture 2083",
        "symbol": "SBID83",
        "sid": 2,
    },
    {
        "i": 894,
        "name": "9% Nepal SBI Bank Rinpatra 2089",
        "symbol": "SBID89",
        "sid": 2,
    },
    {
        "i": 362,
        "name": "10.50% SBL Debenture 2082",
        "symbol": "SBLD2082",
        "sid": 2,
    },
    {
        "i": 360,
        "name": "10.25% SBL Debenture 2083",
        "symbol": "SBLD83",
        "sid": 2,
    },
    {
        "i": 668,
        "name": "8.5% SBL Debenture 2084",
        "symbol": "SBLD84",
        "sid": 2,
    },
    {
        "i": 774,
        "name": "10.75% SBL Debenture 2089",
        "symbol": "SBLD89",
        "sid": 2,
    },
    {
        "i": 819,
        "name": "10.30% Standard Chartered Bank Nepal Ltd Rinpatra",
        "symbol": "SCBD",
        "sid": 2,
    },
    {
        "i": 709,
        "name": "Shangrila Development Bank Debenture 2087",
        "symbol": "SDBD87",
        "sid": 2,
    },
    {
        "i": 361,
        "name": "10.25% Sunrise Bank Debenture 2083",
        "symbol": "SRBLD83",
        "sid": 2,
    }
]
